mixed-port: 7890
allow-lan: true
mode: DIRECT
log-level: info
external-controller: :9090
dns:
  enabled: true
  nameserver:
    - 9.9.9.9
    - 1.1.1.1
    - 4.2.2.1
    - 4.2.2.2
  fallback:
    - 223.5.5.5
