" Author: i314q159
" Date  : 2022.02.17

syntax on
set background=dark

" sets
set number
set showmatch
set encoding=utf-8
set cindent
set autoindent
set showcmd
set title
set ruler
set wildmenu
set laststatus=2
set termguicolors
set cursorline
" set autochdir

" ^no
set noruler
set noeb
set noexpandtab
set noerrorbells
set nowrap
set noswapfile
set nocompatible
set ignorecase smartcase
set noshowmode

" tab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

" maps
let mapleader=";"
nnoremap S :source $MYVIMRC<CR>
map tt :bel term ++close<CR>

" Allow gf to open non-existent file
nnoremap gf :tabedit <cfile><CR>

filetype plugin indent on

" vim-plug
call plug#begin('~/.vim/plugged')
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary'
Plug 'itchyny/vim-gitbranch'
Plug 'othree/html5.vim'
Plug 'itchyny/lightline.vim'
Plug 'mattn/emmet-vim'
Plug 'pbrisbin/vim-mkdir'
Plug 'luochen1990/rainbow'
Plug 'rust-lang/rust.vim'
Plug 'Yggdroot/indentLine'
Plug 'alpertuna/vim-header'
Plug 'vim-scripts/matchit.zip'
Plug 'dracula/vim'
Plug 'vim-test/vim-test'
Plug 'majutsushi/tagbar'
Plug 'ervandew/supertab'
Plug 'Chiel92/vim-autoformat'
call plug#end()

colorscheme dracula

" ervandew/supertab
let g:SuperTabDefaultCompletionType = 'context'

" tpope/vim-commentary
nmap <C-\> gcc

" mattn/emmet-vim'
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall

" itchyny/lightline.vim
let g:lightline = {
            \ 'colorscheme': 'one',
            \ 'active': {
                \   'left': [ [ 'mode', 'paste' ],
                \             [ 'gitbranch', 'filename'] ]
                \ },
                \ 'component_function': {
                    \'gitbranch': 'gitbranch#name'
                    \ }
                    \ }

" luochen1990/rainbow
let g:rainbow_active = 1

" rust-lang/rust.vim'
let g:rustfmt_autosave = 1

" alpertuna/vim-header
nnoremap <leader>d :AddHeader<CR>
let g:header_field_author = 'i314q159'
let g:header_field_modified_by = 0
let g:header_field_modified_timestamp = 0
let g:header_field_timestamp_format = '%Y.%m.%d'

" Yggdroot/indentLine
let g:indentLine_enabled = 1
let g:indentLine_color_term = 110

" Chiel92/vim-autoformat
nmap ff :Autoformat<CR>
