" File  : .vimrc
" Author: i314q159
" Date  : 2022.01.25

syntax on
set background=dark

" sets
set number
" set relativenumber
set autochdir
set encoding=utf-8
set cindent
set autoindent
set showmode
set title
set ruler
set wildmenu
set laststatus=2

" show 8 lines
set scrolloff=8

" ^no
set noruler
set noeb
set nocompatible
set noexpandtab
set noerrorbells
set nowrap
set noswapfile 
set nocompatible

" tab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

" maps
let mapleader=";"
nnoremap ff <ESC>gg=G
nnoremap S :source $MYVIMRC<CR>
" :nnoremap tt :bel :ter++rows=13
nnoremap <leader>t :vert term<CR>

" vim tabbuffer
nnoremap <leader>e :tabedit<SPACE>
nnoremap <leader>c :tabclose<CR>
nnoremap <leader>n :tabNext<CR>

" Allow gf to open non-existent file
nnoremap gf :tabedit <cfile><cr>

" match
" :inoremap ' ''<ESC>i
" :inoremap " ""<ESC>i
" :inoremap ( ()<ESC>i
" :inoremap [ []<ESC>i
" :inoremap { {}<ESC>i
inoremap < <><ESC>i
set showmatch

"netrw tree view 
let g:netrw_liststyle=3

filetype plugin indent on

" vim-plug
call plug#begin('~/.vim/plugged')
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'do': {-> fzf#install()} }
Plug 'junegunn/fzf.vim'
Plug 'itchyny/vim-gitbranch'
Plug 'othree/html5.vim'
Plug 'akhaku/vim-java-unused-imports'
Plug 'itchyny/lightline.vim'
Plug 'mattn/emmet-vim'
Plug 'pbrisbin/vim-mkdir'
Plug 'luochen1990/rainbow'
Plug 'mhinz/vim-startify'
Plug 'rust-lang/rust.vim'
Plug 'Yggdroot/indentLine'
Plug 'fatih/vim-go'
Plug 'alpertuna/vim-header'
call plug#end()

" Bootstrapping vim-plug automatically
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

" tpope/vim-commentary
nmap <C-\> gcc

" mattn/emmet-vim'
let g:user_emmet_install_global = 0
autocmd FileType html,css,jsp EmmetInstall

" itchyny/lightline.vim
" itchyny/vim-gitbranch
let g:lightline = {
            \ 'colorscheme': 'one',
            \ 'active': {
                \   'left': [ [ 'mode', 'paste' ],
                \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
                \ },
                \ 'component_function': {
                    \   'gitbranch': 'gitbranch#name'
                    \ },
                    \ }

" luochen1990/rainbow
let g:rainbow_active = 1

" rust-lang/rust.vim'
let g:rustfmt_autosave = 1

" mhinz/vim-startify
let g:startify_custom_header = 0

" fatih/vim-go
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"

" alpertuna/vim-header
nnoremap <leader>d :AddHeader<CR>
let g:header_field_author = 'i314q159'
let g:header_field_modified_by = 0
let g:header_field_modified_timestamp = 0
let g:header_field_timestamp_format = '%Y.%m.%d'

" junegunn/fzf.vim
nnoremap <leader>f :Files<CR>
nnoremap <leader>g :GFiles<CR>
