# zplug
source /usr/share/zplug/init.zsh

## awesome zsh plugins
zplug "plugins/git", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "rupa/z", use:z.sh
zplug "plugins/extract", from:oh-my-zsh
zplug "themes/simple", from:oh-my-zsh, as:theme
zplug "plugins/colored-man-pages", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh
zplug "paulirish/git-open"

## Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

## zplug load
zplug load

# touchpad natural scrolling
synclient VertScrollDelta=-103
synclient HorizScrollDelta=-103

# zsh_command_not_found
if [[ -x /usr/lib/command-not-found ]] ; then
    if (( ! ${+functions[command_not_found_handler]} )) ; then
        function command_not_found_handler {
            [[ -x /usr/lib/command-not-found ]] || return 1
            /usr/lib/command-not-found -- ${1+"$1"} && :
        }
    fi
fi

# flutter
export PATH="$PATH:/mnt/1T/sdk_d/flutter/bin"
export FLUTTER_STORAGE_BASE_URL="https://mirrors.tuna.tsinghua.edu.cn/flutter"
export PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub"

# golang
export GO111MODE=on
export GOPROXY=https://goproxy.io,direct

# alias
alias bat='batcat'
alias fd='fdfind'
alias gi="vim .gitignore"
alias weather="curl wttr.in"
alias btop="bpytop"

## trash
alias tm="trash"
alias tm-l="trash-list"
alias tm-r="trash-restore"
alias tm-c="trash-empty"

## python
alias pv="virtualenv .venv"

## apt
alias aptud="sudo apt update"
alias aptug="sudo apt upgrade -y"
alias aptli="apt list --installed"
alias apti="sudo apt install -y"
alias apts="apt search --names-only"
alias aptp="sudo apt purge -y"
alias aptc="sudo apt autoremove -y"

## color
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias ip="ip --color=auto"
alias icdiff="icdiff --color=auto"

## ls
alias ll='ls -hl'
alias la='ls -A'
alias l='ls -CF'
alias ls='ls --color=auto'
