source /usr/share/zplug/init.zsh

zplug 'dracula/zsh', as:theme
zplug "plugins/git",   from:oh-my-zsh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# alias
alias bat='batcat'
alias fd='fdfind'
alias tm="trash"
alias py3="python3"
alias ip="ip --color=auto"
alias icdiff="icdiff --color=auto"
alias gi="vim .gitignore"
alias pv="virtualenv .venv"
alias aptud="sudo apt update"
alias aptug="sudo apt upgrade -y"
alias aptlu="apt list --upgradable"
alias aptli="apt list --installed"
alias apti="sudo apt install -y"
alias apts="apt search --names-only"
alias aptp="sudo apt purge -y"
alias weather="curl wttr.in"
