test -s ~/.alias && . ~/.alias || true

# zypper in bash-git-prompt
source /usr/share/bash-git-prompt/gitprompt.sh
GIT_PROMPT_THEME=Single_line

# autojump
source /usr/share/autojump/autojump.bash

# golang
export GO111MODE=on
export GOPROXY=https://goproxy.io,direct

# ibus
ibus-daemon -xrd
