Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.network "public_network"
  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.hostname = "alpine38"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "alpine38"
    vb.gui = false
    vb.cpus = 4
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo cp /etc/apk/repositories /etc/apk/repositories.bp
    sudo sed -i 's#https\?://mirrors.edge.kernel.org/alpine#https://mirror.nju.edu.cn/alpine#g' /etc/apk/repositories
    # sudo apk update
  SHELL
end
